[project]
name = "BFS-maze"
version = "0.1.0"
description = "This is the maze visualization of the BFS algorithm."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]